locale: "ja-JP"  # 日本語を扱うなら変更しておく
title: "CoderDojo 小田原"
timezone: Asia/Tokyo

markdown: kramdown
plugins:
- jekyll-feed

#theme: jekyll-theme-cayman
#theme: jekyll-theme-midnight
#theme: jekyll-theme-slate
#theme: jekyll-theme-minimal
theme: jekyll-theme-minima
#remote_theme: chrisrhymes/bulma-clean-theme
